language: java
jobs:
  include:
    - stage: CodeQuality
      script: ./gradlew sonarqube

// hallo
addons:
  sonarcloud:
    organization: $SONAR_USER
    token:
      secure: $SONAR_TOKEN

jdk:
  - openjdk11
